# Generated by Django 6.0.3 on 2026-03-05 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('recovery_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_image', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('password_reset_code', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
