# Generated by Django 6.0.3 on 2026-03-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(help_text="User's email address", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(help_text="User's first name", max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(help_text="User's last name", max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(help_text="User's phone number", max_length=15),
        ),
    ]
